name: Build and Test or Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Setup V
      uses: prantlf/setup-v-action@v1
      with:
        version: master
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Build
      run: v yaml2json.v
    - name: Test
      run: ./test.sh

  macos:
    runs-on: macos-latest
    steps:
    - name: Setup V
      uses: prantlf/setup-v-action@v1
      with:
        version: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        v install prantlf.cargs
        v install prantlf.jany
        v install prantlf.json
        v install prantlf.yaml
    - name: Build
      run: v yaml2json.v
    - name: Test
      run: ./test.sh

  windows:
    runs-on: windows-latest
    steps:
    - name: Setup V
      uses: prantlf/setup-v-action@v1
      with:
        version: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        v install prantlf.cargs
        v install prantlf.jany
        v install prantlf.json
        v install prantlf.yaml
    - name: Build
      run: v yaml2json.v
